# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :vm1 do |vm1|
    vm1.vm.box = "bento/ubuntu-20.04"
    vm1.vm.network "private_network", ip: "192.168.33.101"
    vm1.vm.synced_folder "./../../guest-share/ubuntu-20.04", "/home/vagrant/share"

    vm1.vm.provision :shell, inline: "bash \"/home/vagrant/share/os/configure.sh\""
    vm1.vm.provision :shell, inline: "bash \"/home/vagrant/share/docker-start.sh\""

    vm1.vm.provider "virtualbox" do |vb|
      vb.name = "ubuntu-20.04"
      vb.cpus = 2
      vb.memory = "4096"
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'VMSVGA']
    end
  end
end
